// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: caUYrhr8rervwyBP2Z2CDy
// Component: fBQBlNLzo0Vc
import * as React from "react";
import {
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  Stack as Stack__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  hasVariant
} from "@plasmicapp/react-web";
import { useDataEnv } from "@plasmicapp/react-web/lib/host";
import NavigationBar from "../../NavigationBar"; // plasmic-import: pTbKwqWvfrOq/component
import { Reveal } from "@plasmicpkgs/react-awesome-reveal";
import ProjectCard from "../../ProjectCard"; // plasmic-import: asxHka0126CP/component
import ContactSection from "../../ContactSection"; // plasmic-import: eqde7z6FWlnM/component
import Footer from "../../Footer"; // plasmic-import: lKvYp9ShH-fD/component
import { useScreenVariants as useScreenVariantsoYDgg1BYrMw } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: o_YDgg1BYrMW/globalVariant
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic.module.css"; // plasmic-import: caUYrhr8rervwyBP2Z2CDy/projectcss
import sty from "./PlasmicHomepage.module.css"; // plasmic-import: fBQBlNLzo0Vc/css
import RightArrowIcon from "./icons/PlasmicIcon__RightArrow"; // plasmic-import: J6fWY7u2ukWC/icon
import StarIcon from "./icons/PlasmicIcon__Star"; // plasmic-import: UZ1cikviYIi0/icon
import uxDesignpngUl1A7AnKMnmE from "./images/uxDesignpng.png"; // plasmic-import: ul1A7anKMnmE/picture
import brushpngStv7UucQhI9 from "./images/brushpng.png"; // plasmic-import: Stv7uucQh-I9/picture
import programmingpngAz9EtswS9YUa from "./images/programmingpng.png"; // plasmic-import: az9EtswS9YUa/picture
import abstractBackgroundJpgPHl10BncVek from "./images/abstractBackgroundJpg.jpg"; // plasmic-import: pHl10BNCVek_/picture
import abstractBackgroundWithSoftGradientColorAndDynamicShadowOnBackgroundBackgroundForWallpaperEps10FreeVectorjpgSjzWdsK53I from "./images/abstractBackgroundWithSoftGradientColorAndDynamicShadowOnBackgroundBackgroundForWallpaperEps10FreeVectorjpg.jpg"; // plasmic-import: sjzWDS-K5_3i/picture
import blueAndOrangeAbstractBackgroundFreeVectorjpg19QiMgtGuDs from "./images/blueAndOrangeAbstractBackgroundFreeVectorjpg.jpg"; // plasmic-import: 19qiMGTGu-DS/picture
import studentGa473640711280JpgAFKduDyOtjPl from "./images/studentGa473640711280Jpg.jpg"; // plasmic-import: aFKduDYOtjPL/picture
import lukePetersB6JiNerWMz0UnsplashjpgPk4HlgewfSmn from "./images/lukePetersB6JiNerWMz0Unsplashjpg.jpg"; // plasmic-import: Pk4hlgewfSMN/picture
import benKoldeBs2Ba7T69MMUnsplashjpg2Maa1DKe7Q from "./images/benKoldeBs2Ba7T69MMUnsplashjpg.jpg"; // plasmic-import: 2-maa-1dKE7q/picture
import danielKorpaiAUmq852V7IUnsplashjpgD62FTqv90Yb from "./images/danielKorpaiAUmq852V7IUnsplashjpg.jpg"; // plasmic-import: d62FTqv9-0yb/picture
import alexSuprunZHvM3XioHoEUnsplashjpgZmoMGssIibe7 from "./images/alexSuprunZHvM3XioHoEUnsplashjpg.jpg"; // plasmic-import: ZmoMGssIibe7/picture
import christopherCampbellRDeoVtE7VOsUnsplashjpgPlsOIxOetfh from "./images/christopherCampbellRDeoVtE7VOsUnsplashjpg.jpg"; // plasmic-import: _PlsOIxOetfh/picture
import courtneyCookTsZo17R3M0SUnsplashjpgFY48Ui3VFQuu from "./images/courtneyCookTsZo17R3M0SUnsplashjpg.jpg"; // plasmic-import: fY48Ui3vFQuu/picture
import alexanderHippIEebWgY6LAUnsplashjpg15KPiDyvVgS6 from "./images/alexanderHippIEebWgY6LAUnsplashjpg.jpg"; // plasmic-import: 15kPiDYVVgS6/picture

createPlasmicElementProxy;

export const PlasmicHomepage__VariantProps = new Array();

export const PlasmicHomepage__ArgProps = new Array();

const $$ = {};

function PlasmicHomepage__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);
  const $props = {
    ...args,
    ...variants
  };
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsoYDgg1BYrMw()
  });
  return (
    <React.Fragment>
      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            sty.root
          )}
        >
          <NavigationBar
            data-plasmic-name={"navigationBar"}
            data-plasmic-override={overrides.navigationBar}
            className={classNames("__wab_instance", sty.navigationBar)}
          />

          <Stack__
            as={"section"}
            data-plasmic-name={"intro"}
            data-plasmic-override={overrides.intro}
            hasGap={true}
            className={classNames(projectcss.all, sty.intro)}
          >
            <div className={classNames(projectcss.all, sty.freeBox__cn72O)}>
              <div
                data-plasmic-name={"mainTextContainer"}
                data-plasmic-override={overrides.mainTextContainer}
                className={classNames(projectcss.all, sty.mainTextContainer)}
              >
                <h1
                  data-plasmic-name={"h1"}
                  data-plasmic-override={overrides.h1}
                  className={classNames(
                    projectcss.all,
                    projectcss.h1,
                    projectcss.__wab_text,
                    sty.h1
                  )}
                >
                  {"Hey there, Anna here \ud83d\udc4b"}
                </h1>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__jpQhg
                  )}
                >
                  {"Web designer and product designer for hire."}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___8C9Zl
                  )}
                >
                  {"Enter some text"}
                </div>
              </div>
              <PlasmicLink__
                data-plasmic-name={"link"}
                data-plasmic-override={overrides.link}
                className={classNames(projectcss.all, projectcss.a, sty.link)}
                href={"#about"}
                platform={"react"}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__leoQr
                  )}
                >
                  {"About me"}
                </div>
                <RightArrowIcon
                  className={classNames(projectcss.all, sty.svg__sb7Kn)}
                  role={"img"}
                />
              </PlasmicLink__>
            </div>
          </Stack__>
          <Stack__
            as={"section"}
            data-plasmic-name={"services"}
            data-plasmic-override={overrides.services}
            hasGap={true}
            className={classNames(projectcss.all, sty.services)}
            id={"Services"}
          >
            <div className={classNames(projectcss.all, sty.freeBox__vTilB)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__pcQjG
                )}
                id={"services"}
              >
                {"Services"}
              </div>
              <h2
                className={classNames(
                  projectcss.all,
                  projectcss.h2,
                  projectcss.__wab_text,
                  sty.h2__im6Ch
                )}
              >
                {"Embracing constraints to push the boundaries."}
              </h2>
            </div>
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.columns__hhDQ)}
            >
              <div className={classNames(projectcss.all, sty.column__akGcP)}>
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__d0Y9Z)}
                  displayHeight={"90px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"90px"}
                  loading={"lazy"}
                  src={{
                    src: uxDesignpngUl1A7AnKMnmE,
                    fullWidth: 512,
                    fullHeight: 512,
                    aspectRatio: undefined
                  }}
                />

                <h3
                  className={classNames(
                    projectcss.all,
                    projectcss.h3,
                    projectcss.__wab_text,
                    sty.h3__tDdf3
                  )}
                >
                  {"UX/UI & Web \nDesign"}
                </h3>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__tGC1
                  )}
                >
                  {
                    "Aut cupiditate expedita dolor eveniet a autem rerum ut dicta. Exercitationem eum suscipit quo. Est fugiat ducimus aut saepe."
                  }
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.column__xTefb)}>
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__oLKcT)}
                  displayHeight={"90px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"90px"}
                  loading={"lazy"}
                  src={{
                    src: brushpngStv7UucQhI9,
                    fullWidth: 512,
                    fullHeight: 512,
                    aspectRatio: undefined
                  }}
                />

                <h3
                  className={classNames(
                    projectcss.all,
                    projectcss.h3,
                    projectcss.__wab_text,
                    sty.h3__nzVp4
                  )}
                >
                  {"Branding & visual \ndesign"}
                </h3>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___88TqR
                  )}
                >
                  {
                    "Aut cupiditate expedita dolor eveniet a autem rerum ut dicta. Exercitationem eum suscipit quo. Est fugiat ducimus aut saepe."
                  }
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.column__mjIm5)}>
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__ojX01)}
                  displayHeight={"90px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"90px"}
                  loading={"lazy"}
                  src={{
                    src: programmingpngAz9EtswS9YUa,
                    fullWidth: 512,
                    fullHeight: 512,
                    aspectRatio: undefined
                  }}
                />

                <h3
                  className={classNames(
                    projectcss.all,
                    projectcss.h3,
                    projectcss.__wab_text,
                    sty.h3__mplzH
                  )}
                >
                  {"Web \ndevelopment"}
                </h3>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__to8E
                  )}
                >
                  {
                    "Aut cupiditate expedita dolor eveniet a autem rerum ut dicta. Exercitationem eum suscipit quo. Est fugiat ducimus aut saepe."
                  }
                </div>
              </div>
            </Stack__>
          </Stack__>
          <Stack__
            as={"section"}
            data-plasmic-name={"work"}
            data-plasmic-override={overrides.work}
            hasGap={true}
            className={classNames(projectcss.all, sty.work)}
            id={"work"}
          >
            <div className={classNames(projectcss.all, sty.freeBox__hhyeG)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__irMaC
                )}
                id={"services"}
              >
                {"work"}
              </div>
              <h2
                className={classNames(
                  projectcss.all,
                  projectcss.h2,
                  projectcss.__wab_text,
                  sty.h2__vsAq6
                )}
              >
                {"Privileged to work with on some amazing projects."}
              </h2>
            </div>
            <div className={classNames(projectcss.all, sty.freeBox__k9DJh)}>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.columns___7Bo95)}
              >
                <div className={classNames(projectcss.all, sty.column__f27Pv)}>
                  <Reveal
                    className={classNames("__wab_instance", sty.reveal__ayBcf)}
                    direction={"up"}
                    duration={500}
                    triggerOnce={true}
                  >
                    <ProjectCard
                      className={classNames(
                        "__wab_instance",
                        sty.projectCard__mn22D
                      )}
                      link={`/project-relaunch`}
                      title={"Project Relaunch"}
                    />
                  </Reveal>
                </div>
                <div className={classNames(projectcss.all, sty.column__qgzcM)}>
                  <Reveal
                    className={classNames("__wab_instance", sty.reveal__puei)}
                    delay={250}
                    direction={"up"}
                    duration={500}
                    triggerOnce={true}
                  >
                    <ProjectCard
                      className={classNames(
                        "__wab_instance",
                        sty.projectCard__xaunz
                      )}
                      description={
                        "Aut cupiditate expedita dolor eveniet a autem rerum ut dicta. Exercitationem eum suscipit quo. Est fugiat ducimus aut saepe."
                      }
                      image={{
                        src: abstractBackgroundJpgPHl10BncVek,
                        fullWidth: 1920,
                        fullHeight: 1171,
                        aspectRatio: undefined
                      }}
                      link={`/website-redesign`}
                      title={"Website Redesign"}
                    />
                  </Reveal>
                </div>
              </Stack__>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.columns__rIxhs)}
              >
                <div className={classNames(projectcss.all, sty.column__iwNy6)}>
                  <Reveal
                    className={classNames("__wab_instance", sty.reveal__juLmv)}
                    delay={500}
                    direction={"up"}
                    duration={500}
                    triggerOnce={true}
                  >
                    <ProjectCard
                      className={classNames(
                        "__wab_instance",
                        sty.projectCard__wfLj
                      )}
                      description={
                        "Aut cupiditate expedita dolor eveniet a autem rerum ut dicta. Exercitationem eum suscipit quo. Est fugiat ducimus aut saepe."
                      }
                      image={{
                        src: abstractBackgroundWithSoftGradientColorAndDynamicShadowOnBackgroundBackgroundForWallpaperEps10FreeVectorjpgSjzWdsK53I,
                        fullWidth: 1920,
                        fullHeight: 1080,
                        aspectRatio: undefined
                      }}
                      link={`/premium-sass-design`}
                      title={"Premium Saas Design"}
                    />
                  </Reveal>
                </div>
                <div className={classNames(projectcss.all, sty.column__nsjfq)}>
                  <Reveal
                    className={classNames("__wab_instance", sty.reveal__k2DYs)}
                    delay={750}
                    direction={"up"}
                    duration={500}
                    triggerOnce={true}
                  >
                    <ProjectCard
                      className={classNames(
                        "__wab_instance",
                        sty.projectCard___81YmA
                      )}
                      description={
                        "Aut cupiditate expedita dolor eveniet a autem rerum ut dicta. Exercitationem eum suscipit quo. Est fugiat ducimus aut saepe."
                      }
                      image={{
                        src: blueAndOrangeAbstractBackgroundFreeVectorjpg19QiMgtGuDs,
                        fullWidth: 1920,
                        fullHeight: 1280,
                        aspectRatio: undefined
                      }}
                      link={`/web-visual-design`}
                      title={"Web Visual Graphic Design"}
                    />
                  </Reveal>
                </div>
              </Stack__>
            </div>
          </Stack__>
          <Stack__
            as={"section"}
            data-plasmic-name={"about"}
            data-plasmic-override={overrides.about}
            hasGap={true}
            className={classNames(projectcss.all, sty.about)}
            id={"about"}
          >
            <div className={classNames(projectcss.all, sty.freeBox__qtou)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___4BIty
                )}
                id={"about"}
              >
                {"About Me"}
              </div>
            </div>
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__cqfJ)}
            >
              <h2
                className={classNames(
                  projectcss.all,
                  projectcss.h2,
                  projectcss.__wab_text,
                  sty.h2__mouAn
                )}
              >
                {"Bridging design and no-code."}
              </h2>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__pcnM
                )}
              >
                {
                  "Anna is an award winning, web designer specialising in no-code solutions. With over 8 years of professional experience I've helped countless startups launch & grow their business."
                }
              </div>
            </Stack__>
            <div className={classNames(projectcss.all, sty.freeBox__sT6K3)}>
              <div className={classNames(projectcss.all, sty.freeBox__lfp3U)}>
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox___2N5Fg)}
                >
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__txR7Q)}
                    displayHeight={
                      hasVariant(globalVariants, "screen", "mobileOnly")
                        ? "311px"
                        : "312px"
                    }
                    displayMaxHeight={"none"}
                    displayMaxWidth={
                      hasVariant(globalVariants, "screen", "mobileOnly")
                        ? "100%"
                        : "100%"
                    }
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={
                      hasVariant(globalVariants, "screen", "mobileOnly")
                        ? "100%"
                        : "100%"
                    }
                    loading={"lazy"}
                    src={{
                      src: studentGa473640711280JpgAFKduDyOtjPl,
                      fullWidth: 1280,
                      fullHeight: 853,
                      aspectRatio: undefined
                    }}
                  />

                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__jsl7R)}
                    displayHeight={"312px"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={
                      hasVariant(globalVariants, "screen", "mobileOnly")
                        ? "100%"
                        : "100%"
                    }
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"100%"}
                    loading={"lazy"}
                    src={{
                      src: lukePetersB6JiNerWMz0UnsplashjpgPk4HlgewfSmn,
                      fullWidth: 1920,
                      fullHeight: 1280,
                      aspectRatio: undefined
                    }}
                  />
                </Stack__>
              </div>
              <div className={classNames(projectcss.all, sty.freeBox__goL4G)}>
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__le8Ff)}
                  displayHeight={"100%"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={
                    hasVariant(globalVariants, "screen", "mobileOnly")
                      ? "100%"
                      : "100%"
                  }
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={
                    hasVariant(globalVariants, "screen", "mobileOnly")
                      ? "100%"
                      : "100%"
                  }
                  loading={"lazy"}
                  src={{
                    src: benKoldeBs2Ba7T69MMUnsplashjpg2Maa1DKe7Q,
                    fullWidth: 1920,
                    fullHeight: 2449,
                    aspectRatio: undefined
                  }}
                />
              </div>
              <div className={classNames(projectcss.all, sty.freeBox__xFbCg)}>
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__ctaFv)}
                  displayHeight={"100%"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={
                    hasVariant(globalVariants, "screen", "mobileOnly")
                      ? "100%"
                      : "100%"
                  }
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={
                    hasVariant(globalVariants, "screen", "mobileOnly")
                      ? "100%"
                      : "100%"
                  }
                  loading={"lazy"}
                  src={{
                    src: danielKorpaiAUmq852V7IUnsplashjpgD62FTqv90Yb,
                    fullWidth: 1920,
                    fullHeight: 2400,
                    aspectRatio: undefined
                  }}
                />
              </div>
            </div>
          </Stack__>
          <Stack__
            as={"section"}
            data-plasmic-name={"testimonials"}
            data-plasmic-override={overrides.testimonials}
            hasGap={true}
            className={classNames(projectcss.all, sty.testimonials)}
          >
            <div className={classNames(projectcss.all, sty.freeBox__bjLFv)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__cpubA
                )}
              >
                {"TESTIMONIALS"}
              </div>
              <h2
                className={classNames(
                  projectcss.all,
                  projectcss.h2,
                  projectcss.__wab_text,
                  sty.h2__dntpt
                )}
              >
                {"Hear from the folks I've worked with."}
              </h2>
            </div>
            <div className={classNames(projectcss.all, sty.freeBox__ibQdT)}>
              <div className={classNames(projectcss.all, sty.freeBox__o1Ac)}>
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__yw9Rm)}
                >
                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__qe3Hs)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__r0Ogb)}
                    >
                      <StarIcon
                        className={classNames(projectcss.all, sty.svg__p0Qqe)}
                        role={"img"}
                      />

                      <StarIcon
                        className={classNames(projectcss.all, sty.svg__xiPu5)}
                        role={"img"}
                      />

                      <StarIcon
                        className={classNames(projectcss.all, sty.svg__dpgDf)}
                        role={"img"}
                      />

                      <StarIcon
                        className={classNames(projectcss.all, sty.svg__sYjN7)}
                        role={"img"}
                      />

                      <StarIcon
                        className={classNames(projectcss.all, sty.svg__h0Tx)}
                        role={"img"}
                      />
                    </div>
                    <h3
                      className={classNames(
                        projectcss.all,
                        projectcss.h3,
                        projectcss.__wab_text,
                        sty.h3__x8AMt
                      )}
                    >
                      {"Very experienced"}
                    </h3>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___9IYZ
                      )}
                    >
                      {
                        '"Anna worked very closely with us, delivering such a well designed product. Great communication and quick turn around. Loved it!"'
                      }
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.columns__seGar)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column___84Okl
                        )}
                      >
                        <PlasmicImg__
                          alt={""}
                          className={classNames(sty.img___2B2P)}
                          displayHeight={"100px"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"100px"}
                          loading={"lazy"}
                          src={{
                            src: alexSuprunZHvM3XioHoEUnsplashjpgZmoMGssIibe7,
                            fullWidth: 640,
                            fullHeight: 640,
                            aspectRatio: undefined
                          }}
                        />
                      </div>
                      <div
                        className={classNames(projectcss.all, sty.column__wjNw)}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__yp3Nm
                          )}
                        >
                          {"Albert David"}
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__yjxE5
                          )}
                        >
                          {"Marketing Manager, Company"}
                        </div>
                      </div>
                    </div>
                  </Stack__>
                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__dZjDi)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__i70H3)}
                    >
                      <StarIcon
                        className={classNames(projectcss.all, sty.svg__cyIxk)}
                        role={"img"}
                      />

                      <StarIcon
                        className={classNames(projectcss.all, sty.svg__nlej5)}
                        role={"img"}
                      />

                      <StarIcon
                        className={classNames(projectcss.all, sty.svg__jmUsC)}
                        role={"img"}
                      />

                      <StarIcon
                        className={classNames(projectcss.all, sty.svg___2SfU8)}
                        role={"img"}
                      />

                      <StarIcon
                        className={classNames(projectcss.all, sty.svg__etrJ4)}
                        role={"img"}
                      />
                    </div>
                    <h3
                      className={classNames(
                        projectcss.all,
                        projectcss.h3,
                        projectcss.__wab_text,
                        sty.h3__xLiNm
                      )}
                    >
                      {"Very fast & skillful"}
                    </h3>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__zXv7M
                      )}
                    >
                      {
                        '"Anna worked very closely with us, delivering such a well designed product. Great communication and quick turn around. Loved it!"'
                      }
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.columns__adUo7)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__r4Fjd
                        )}
                      >
                        <PlasmicImg__
                          alt={""}
                          className={classNames(sty.img__zgMcS)}
                          displayHeight={"100px"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"100px"}
                          loading={"lazy"}
                          src={{
                            src: christopherCampbellRDeoVtE7VOsUnsplashjpgPlsOIxOetfh,
                            fullWidth: 640,
                            fullHeight: 427,
                            aspectRatio: undefined
                          }}
                        />
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__wlLYv
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__dC7RJ
                          )}
                        >
                          {"Arolina"}
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__jcUIo
                          )}
                        >
                          {"Manager, Company"}
                        </div>
                      </div>
                    </div>
                  </Stack__>
                </Stack__>
              </div>
              <div className={classNames(projectcss.all, sty.freeBox___8Jy1K)}>
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__sH32A)}
                >
                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__jW8Ji)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__xQxy4)}
                    >
                      <StarIcon
                        className={classNames(projectcss.all, sty.svg__aXjA9)}
                        role={"img"}
                      />

                      <StarIcon
                        className={classNames(projectcss.all, sty.svg___5HA0W)}
                        role={"img"}
                      />

                      <StarIcon
                        className={classNames(projectcss.all, sty.svg__qTl9T)}
                        role={"img"}
                      />

                      <StarIcon
                        className={classNames(projectcss.all, sty.svg__jwirS)}
                        role={"img"}
                      />

                      <StarIcon
                        className={classNames(projectcss.all, sty.svg__f4Mmo)}
                        role={"img"}
                      />
                    </div>
                    <h3
                      className={classNames(
                        projectcss.all,
                        projectcss.h3,
                        projectcss.__wab_text,
                        sty.h3__eHutk
                      )}
                    >
                      {"skilled communicator"}
                    </h3>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__dPgPe
                      )}
                    >
                      {
                        '"Anna worked very closely with us, delivering such a well designed product. Great communication and quick turn around. Loved it!"'
                      }
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.columns__qAhB1)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__e9YGn
                        )}
                      >
                        <PlasmicImg__
                          alt={""}
                          className={classNames(sty.img__wXwdP)}
                          displayHeight={"100px"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"100px"}
                          loading={"lazy"}
                          src={{
                            src: courtneyCookTsZo17R3M0SUnsplashjpgFY48Ui3VFQuu,
                            fullWidth: 640,
                            fullHeight: 960,
                            aspectRatio: undefined
                          }}
                        />
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__zaxwH
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__u4T4
                          )}
                        >
                          {"Firmona"}
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__mfzRm
                          )}
                        >
                          {"Founder, Company"}
                        </div>
                      </div>
                    </div>
                  </Stack__>
                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox___057Wn)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__yuCoZ)}
                    >
                      <StarIcon
                        className={classNames(projectcss.all, sty.svg__ekmO)}
                        role={"img"}
                      />

                      <StarIcon
                        className={classNames(projectcss.all, sty.svg__l6Xos)}
                        role={"img"}
                      />

                      <StarIcon
                        className={classNames(projectcss.all, sty.svg__hzOdx)}
                        role={"img"}
                      />

                      <StarIcon
                        className={classNames(projectcss.all, sty.svg__mVyJw)}
                        role={"img"}
                      />

                      <StarIcon
                        className={classNames(projectcss.all, sty.svg__qq4OP)}
                        role={"img"}
                      />
                    </div>
                    <h3
                      className={classNames(
                        projectcss.all,
                        projectcss.h3,
                        projectcss.__wab_text,
                        sty.h3__beXne
                      )}
                    >
                      {"Great design skills"}
                    </h3>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__oVive
                      )}
                    >
                      {
                        '"Anna worked very closely with us, delivering such a well designed product. Great communication and quick turn around. Loved it!"'
                      }
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        sty.columns___9UvQb
                      )}
                    >
                      <div
                        className={classNames(projectcss.all, sty.column__hmOj)}
                      >
                        <PlasmicImg__
                          alt={""}
                          className={classNames(sty.img__kdAcy)}
                          displayHeight={"100px"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"100px"}
                          loading={"lazy"}
                          src={{
                            src: alexanderHippIEebWgY6LAUnsplashjpg15KPiDyvVgS6,
                            fullWidth: 640,
                            fullHeight: 640,
                            aspectRatio: undefined
                          }}
                        />
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__gQcBn
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text___9VkVi
                          )}
                        >
                          {"Motherson"}
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__imMtF
                          )}
                        >
                          {"Design Lead, Company"}
                        </div>
                      </div>
                    </div>
                  </Stack__>
                </Stack__>
              </div>
            </div>
          </Stack__>
          <ContactSection
            data-plasmic-name={"contactSection"}
            data-plasmic-override={overrides.contactSection}
            className={classNames("__wab_instance", sty.contactSection)}
          />

          <Footer
            data-plasmic-name={"footer"}
            data-plasmic-override={overrides.footer}
            className={classNames("__wab_instance", sty.footer)}
          />
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "navigationBar",
    "intro",
    "mainTextContainer",
    "h1",
    "link",
    "services",
    "work",
    "about",
    "testimonials",
    "contactSection",
    "footer"
  ],

  navigationBar: ["navigationBar"],
  intro: ["intro", "mainTextContainer", "h1", "link"],
  mainTextContainer: ["mainTextContainer", "h1"],
  h1: ["h1"],
  link: ["link"],
  services: ["services"],
  work: ["work"],
  about: ["about"],
  testimonials: ["testimonials"],
  contactSection: ["contactSection"],
  footer: ["footer"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicHomepage__ArgProps,
          internalVariantPropNames: PlasmicHomepage__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicHomepage__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHomepage";
  } else {
    func.displayName = `PlasmicHomepage.${nodeName}`;
  }
  return func;
}

export const PlasmicHomepage = Object.assign(
  // Top-level PlasmicHomepage renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    navigationBar: makeNodeComponent("navigationBar"),
    intro: makeNodeComponent("intro"),
    mainTextContainer: makeNodeComponent("mainTextContainer"),
    h1: makeNodeComponent("h1"),
    link: makeNodeComponent("link"),
    services: makeNodeComponent("services"),
    work: makeNodeComponent("work"),
    about: makeNodeComponent("about"),
    testimonials: makeNodeComponent("testimonials"),
    contactSection: makeNodeComponent("contactSection"),
    footer: makeNodeComponent("footer"),
    // Metadata about props expected for PlasmicHomepage
    internalVariantProps: PlasmicHomepage__VariantProps,
    internalArgProps: PlasmicHomepage__ArgProps,
    // Page metadata
    pageMetadata: {
      title: "Anna.Design",
      description:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim in eros elementum tristique. Duis cursus, mi quis viverra ornare, eros dolor interdum nulla, ut commodo diam libero vitae erat. Aenean faucibus nibh et justo cursus id rutrum lorem imperdiet. Nunc ut sem vitae risus tristique posuere.",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicHomepage;
/* prettier-ignore-end */
